### ISSUE TITLE
ex!

### ISSUE THREAD

**Issue by vasilisvg** [meesrutten/cssttr#5]
https://github.com/meesrutten/cssttr/blob/bba3b5ed42fad8cc4e50f572ff1cab048e210966/styles.css#L220
Leuke unit. Ken je de `ch`? Die is misschien nog beter voor deze use-case: dat is de daadwerkelijke breedte van de 0 (nul) van het gebruikte font. Ik weet niet zeker of de `ex` ook de hoogte is van het gebruikte font of een vaste maat zoals de `em`

**Comment by meesrutten** [comment]
Klopt!
Fixed
