### ISSUE TITLE
:valid :invalid

### ISSUE THREAD

**Issue by vasilisvg** [meesrutten/cssttr#6]
https://github.com/meesrutten/cssttr/blob/bba3b5ed42fad8cc4e50f572ff1cab048e210966/styles.css#L264
Wist je dat je `:valid` en `:invalid` ook op een `fieldset` en een `form` kunt zetten? Zie deze pen van Joost: https://codepen.io/joostf/pen/VKyPxk

**Comment by meesrutten** [comment]
Fixed!
