### ISSUE TITLE
Benieuwd

### ISSUE THREAD

**Issue by vasilisvg** [meesrutten/cssttr#8]
https://github.com/meesrutten/cssttr/blob/bba3b5ed42fad8cc4e50f572ff1cab048e210966/styles.css#L404
Ik ben heel benieuwd naar hoe het er uitziet! De code ziet er in elk geval heel mooi uit. Je bent lekker aan het experimenteren. Ga zo door!

**Comment by meesrutten** [comment]
https://meesrutten.me/minor/cssttr/styleguide.html
